# .github/workflows/docker-build.yml
name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # Every day at 2 AM UTC

jobs:
  docker-build:
    name: Build dev/latest Dockerfile
    if: github.repository == 'NCAR/wrf_hydro_docker'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t wrfhydro/dev:latest -f dev/latest/Dockerfile .
