name: build

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1'  # Every day at 2 AM UTC

jobs:
  docker-build:
    name: Build Dockerfiles
    if: github.repository == 'NCAR/wrf_hydro_docker'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build base Docker image
        run: |
          docker build -t wrfhydro/dev:base dev/base

      - name: Build release Docker image
        run: |
          docker build -t wrfhydro/dev:release dev/release

      - name: Build latest Docker image
        run: |
          docker build -t wrfhydro/dev:latest dev/latest
